# This is the item id of the portal creation wand.
# If you are using WorldEdit. Changing this will have NO EFFECT.
wand: 271
useonmove: true
portalsdefaulttonether: false
enforceportalaccess: true
portalcooldown: 1000
version: 2.6
